-- ==========================================
-- TRUNCATE STAGING TABLES
-- ==========================================

USE DATABASE B2B_EVENT_TICKETING;

TRUNCATE TABLE RAW.STG_COMMISSION_AGREEMENTS;
TRUNCATE TABLE RAW.STG_CUSTOMERS;
TRUNCATE TABLE RAW.STG_EVENTS;
TRUNCATE TABLE RAW.STG_ORGANIZERS;
TRUNCATE TABLE RAW.STG_RESELLERS;
TRUNCATE TABLE RAW.STG_TICKET_SALES;

-- ==========================================
-- TRUNCATE MAIN RAW TABLES
-- Child tables first to avoid FK issues
-- ==========================================

TRUNCATE TABLE RAW.TICKET_SALES;
TRUNCATE TABLE RAW.COMMISSION_AGREEMENTS;
TRUNCATE TABLE RAW.CUSTOMERS;
TRUNCATE TABLE RAW.EVENTS;
TRUNCATE TABLE RAW.ORGANIZERS;
TRUNCATE TABLE RAW.RESELLERS;

-----------------------------------

--update the etl_watermark table

UPDATE B2B_EVENT_TICKETING.AUDIT.ETL_WATERMARK
SET LAST_UPDATED_AT='1900-01-01 00:00:00';


-- reseller daily sales table --
TRUNCATE TABLE B2B_EVENT_TICKETING.RAW.RESELLER_DAILY_SALES;
TRUNCATE TABLE B2B_EVENT_TICKETING.AUDIT.FILE_LOAD_HISTORY;


----------------------------------------

INSERT INTO AUDIT.ETL_WATERMARK
(
    SOURCE_TABLE,
    LAST_UPDATED_AT
)
VALUES
    ('ORGANIZERS', '1900-01-01 00:00:00'),
    ('RESELLERS', '1900-01-01 00:00:00'),
    ('CUSTOMERS', '1900-01-01 00:00:00'),
    ('EVENTS', '1900-01-01 00:00:00'),
    ('COMMISSION_AGREEMENTS', '1900-01-01 00:00:00'),
    ('TICKET_SALES', '1900-01-01 00:00:00');

--------------------------------------------------------------------------