USE ROLE ACCOUNTADMIN;
CREATE WAREHOUSE IF NOT EXISTS COMPUTE_WH WAREHOUSE_SIZE = XSMALL AUTO_SUSPEND = 60 AUTO_RESUME = TRUE INITIALLY_SUSPENDED = TRUE;
CREATE DATABASE IF NOT EXISTS TICKETING_DB;
CREATE SCHEMA IF NOT EXISTS TICKETING_DB.RAW;
CREATE SCHEMA IF NOT EXISTS TICKETING_DB.STAGING;
CREATE SCHEMA IF NOT EXISTS TICKETING_DB.MART;
CREATE SCHEMA IF NOT EXISTS TICKETING_DB.AUDIT;
