
-- ============================================================
-- DATABASE & SCHEMAS
-- ============================================================

CREATE DATABASE IF NOT EXISTS B2B_EVENT_TICKETING;
USE DATABASE B2B_EVENT_TICKETING;
CREATE SCHEMA IF NOT EXISTS RAW;
USE SCHEMA RAW;

-- ============================================================
-- RAW TABLES - POSTGRES SOURCE SYSTEM
-- ============================================================

CREATE OR REPLACE TABLE RAW.ORGANIZERS (
ORGANIZER_ID STRING,
ORGANIZER_NAME STRING,
COUNTRY STRING,
REGION STRING,


LOAD_TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
SOURCE_SYSTEM STRING DEFAULT 'POSTGRES'


);

CREATE OR REPLACE TABLE RAW.RESELLERS (
RESELLER_ID STRING,
RESELLER_NAME STRING,
COUNTRY STRING,
REGION STRING,


LOAD_TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
SOURCE_SYSTEM STRING DEFAULT 'POSTGRES'


);

CREATE OR REPLACE TABLE RAW.COMMISSION_AGREEMENTS (
AGREEMENT_ID NUMBER,
ORGANIZER_ID STRING,
RESELLER_ID STRING,


COMMISSION_RATE NUMBER(5,2),

EFFECTIVE_FROM DATE,
EFFECTIVE_TO DATE,

LOAD_TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
SOURCE_SYSTEM STRING DEFAULT 'POSTGRES'
UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),


);

CREATE OR REPLACE TABLE RAW.EVENTS (
EVENT_ID STRING,
ORGANIZER_ID STRING,


EVENT_NAME STRING,
EVENT_TYPE STRING,

VENUE STRING,
REGION STRING,

EVENT_DATE DATE,

LOAD_TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
SOURCE_SYSTEM STRING DEFAULT 'POSTGRES'


);

CREATE OR REPLACE TABLE RAW.CUSTOMERS (
CUSTOMER_ID STRING,


FIRST_NAME STRING,
LAST_NAME STRING,

EMAIL STRING,

COUNTRY STRING,

LOAD_TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
SOURCE_SYSTEM STRING DEFAULT 'POSTGRES'


);

CREATE OR REPLACE TABLE RAW.TICKET_SALES (
TICKET_ID STRING,


EVENT_ID STRING,
CUSTOMER_ID STRING,
RESELLER_ID STRING,

SALES_CHANNEL STRING,

QUANTITY NUMBER,
UNIT_PRICE NUMBER(10,2),
TOTAL_AMOUNT NUMBER(12,2),

PURCHASE_DATE DATE,

LOAD_TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
SOURCE_SYSTEM STRING DEFAULT 'POSTGRES'


);

-- ============================================================
-- RAW TABLE - RESELLER CSV SOURCE
-- ============================================================

CREATE OR REPLACE TABLE RAW.RESELLER_DAILY_SALES (
TRANSACTION_ID NUMBER,


RESELLER_ID STRING,

EVENT_NAME STRING,

NUMBER_OF_PURCHASED_TICKETS NUMBER,

TOTAL_AMOUNT NUMBER(12,2),

SALES_CHANNEL STRING,

CUSTOMER_FIRST_NAME STRING,
CUSTOMER_LAST_NAME STRING,

OFFICE_LOCATION STRING,

CREATED_DATE DATE,

SOURCE_FILE_NAME STRING,

LOAD_TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),

SOURCE_SYSTEM STRING DEFAULT 'CSV'


);

-- ============================================================
-- OPTIONAL RAW LOAD AUDIT TABLE
-- ============================================================

CREATE OR REPLACE TABLE RAW.LOAD_AUDIT (
LOAD_ID NUMBER AUTOINCREMENT,


SOURCE_SYSTEM STRING,
SOURCE_OBJECT STRING,

LOAD_START_TIME TIMESTAMP_NTZ,
LOAD_END_TIME TIMESTAMP_NTZ,

RECORDS_READ NUMBER,
RECORDS_LOADED NUMBER,
RECORDS_REJECTED NUMBER,

STATUS STRING,

CREATED_TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()


);

-- ============================================================
-- OPTIONAL FILE TRACKING TABLE
-- ============================================================

CREATE OR REPLACE TABLE RAW.FILE_HISTORY (
FILE_NAME STRING,


SOURCE_SYSTEM STRING,

FILE_DATE DATE,

LOAD_TIMESTAMP TIMESTAMP_NTZ,

RECORD_COUNT NUMBER,

STATUS STRING


);

-- ============================================================
-- VERIFY OBJECTS
-- ============================================================

SHOW TABLES IN SCHEMA RAW;

CREATE SCHEMA IF NOT EXISTS AUDIT;

CREATE TABLE AUDIT.FILE_LOAD_HISTORY
(
    FILE_NAME VARCHAR,
    FILE_SHA VARCHAR,
    LOAD_DATE TIMESTAMP,
    RECORD_COUNT INTEGER,
    STATUS VARCHAR,
    ERROR_MESSAGE VARCHAR
);


CREATE TABLE AUDIT.JOB_AUDIT
(
    JOB_NAME VARCHAR,
    START_TIME TIMESTAMP,
    END_TIME TIMESTAMP,
    STATUS VARCHAR,
    RECORDS_LOADED INTEGER,
    FILES_PROCESSED INTEGER,
    ERROR_MESSAGE VARCHAR
);
