USE DATABASE TICKETING_DB;
USE SCHEMA AUDIT;
CREATE TABLE IF NOT EXISTS ETL_BATCH_RUN (batch_id VARCHAR PRIMARY KEY, pipeline_name VARCHAR, status VARCHAR, started_at TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP, finished_at TIMESTAMP_NTZ, error_message VARCHAR);
CREATE TABLE IF NOT EXISTS ETL_WATERMARK (source_name VARCHAR PRIMARY KEY, last_successful_watermark TIMESTAMP_NTZ, updated_at TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS FILE_INGESTION_LOG (file_name VARCHAR PRIMARY KEY, reseller_id VARCHAR, file_sale_date DATE, batch_id VARCHAR, status VARCHAR, row_count NUMBER, loaded_at TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP, error_message VARCHAR);
CREATE TABLE IF NOT EXISTS REJECTED_RECORDS (rejected_id NUMBER AUTOINCREMENT, batch_id VARCHAR, source_name VARCHAR, source_file VARCHAR, reason VARCHAR, raw_payload VARIANT, rejected_at TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS DATA_QUALITY_LOG (dq_id NUMBER AUTOINCREMENT, batch_id VARCHAR, check_name VARCHAR, table_name VARCHAR, status VARCHAR, failed_count NUMBER, checked_at TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP);
