-- ============================================================
-- ORGANIZERS
-- ============================================================

MERGE INTO RAW.ORGANIZERS T
USING RAW.STG_ORGANIZERS S

ON T.ORGANIZER_ID = S.ORGANIZER_ID


WHEN MATCHED THEN UPDATE SET

T.ORGANIZER_NAME = S.ORGANIZER_NAME,
T.COUNTRY = S.COUNTRY,
T.REGION = S.REGION,
T.LOAD_TS = S.LOAD_TS,
T.SOURCE_SYSTEM = S.SOURCE_SYSTEM,
T.BATCH_ID = S.BATCH_ID,
T.UPDATED_AT = S.UPDATED_AT


WHEN NOT MATCHED THEN INSERT
(
ORGANIZER_ID,
ORGANIZER_NAME,
COUNTRY,
REGION,
LOAD_TS,
SOURCE_SYSTEM,
BATCH_ID,
UPDATED_AT
)

VALUES
(
S.ORGANIZER_ID,
S.ORGANIZER_NAME,
S.COUNTRY,
S.REGION,
S.LOAD_TS,
S.SOURCE_SYSTEM,
S.BATCH_ID,
S.UPDATED_AT
);



-- ============================================================
-- RESELLERS
-- ============================================================

MERGE INTO RAW.RESELLERS T
USING RAW.STG_RESELLERS S

ON T.RESELLER_ID = S.RESELLER_ID


WHEN MATCHED THEN UPDATE SET

T.RESELLER_NAME = S.RESELLER_NAME,
T.COUNTRY = S.COUNTRY,
T.REGION = S.REGION,
T.LOAD_TS = S.LOAD_TS,
T.SOURCE_SYSTEM = S.SOURCE_SYSTEM,
T.BATCH_ID = S.BATCH_ID,
T.UPDATED_AT = S.UPDATED_AT


WHEN NOT MATCHED THEN INSERT
(
RESELLER_ID,
RESELLER_NAME,
COUNTRY,
REGION,
LOAD_TS,
SOURCE_SYSTEM,
BATCH_ID,
UPDATED_AT
)

VALUES
(
S.RESELLER_ID,
S.RESELLER_NAME,
S.COUNTRY,
S.REGION,
S.LOAD_TS,
S.SOURCE_SYSTEM,
S.BATCH_ID,
S.UPDATED_AT
);



-- ============================================================
-- CUSTOMERS
-- ============================================================

MERGE INTO RAW.CUSTOMERS T
USING RAW.STG_CUSTOMERS S

ON T.CUSTOMER_ID = S.CUSTOMER_ID


WHEN MATCHED THEN UPDATE SET

T.FIRST_NAME = S.FIRST_NAME,
T.LAST_NAME = S.LAST_NAME,
T.EMAIL = S.EMAIL,
T.COUNTRY = S.COUNTRY,
T.LOAD_TS = S.LOAD_TS,
T.SOURCE_SYSTEM = S.SOURCE_SYSTEM,
T.BATCH_ID = S.BATCH_ID,
T.UPDATED_AT = S.UPDATED_AT


WHEN NOT MATCHED THEN INSERT
(
CUSTOMER_ID,
FIRST_NAME,
LAST_NAME,
EMAIL,
COUNTRY,
LOAD_TS,
SOURCE_SYSTEM,
BATCH_ID,
UPDATED_AT
)

VALUES
(
S.CUSTOMER_ID,
S.FIRST_NAME,
S.LAST_NAME,
S.EMAIL,
S.COUNTRY,
S.LOAD_TS,
S.SOURCE_SYSTEM,
S.BATCH_ID,
S.UPDATED_AT
);



-- ============================================================
-- EVENTS
-- ============================================================

MERGE INTO RAW.EVENTS T
USING RAW.STG_EVENTS S

ON T.EVENT_ID = S.EVENT_ID


WHEN MATCHED THEN UPDATE SET

T.ORGANIZER_ID = S.ORGANIZER_ID,
T.EVENT_NAME = S.EVENT_NAME,
T.EVENT_TYPE = S.EVENT_TYPE,
T.VENUE = S.VENUE,
T.REGION = S.REGION,
T.EVENT_DATE = S.EVENT_DATE,
T.LOAD_TS = S.LOAD_TS,
T.SOURCE_SYSTEM = S.SOURCE_SYSTEM,
T.BATCH_ID = S.BATCH_ID,
T.UPDATED_AT = S.UPDATED_AT


WHEN NOT MATCHED THEN INSERT
(
EVENT_ID,
ORGANIZER_ID,
EVENT_NAME,
EVENT_TYPE,
VENUE,
REGION,
EVENT_DATE,
LOAD_TS,
SOURCE_SYSTEM,
BATCH_ID,
UPDATED_AT
)

VALUES
(
S.EVENT_ID,
S.ORGANIZER_ID,
S.EVENT_NAME,
S.EVENT_TYPE,
S.VENUE,
S.REGION,
S.EVENT_DATE,
S.LOAD_TS,
S.SOURCE_SYSTEM,
S.BATCH_ID,
S.UPDATED_AT
);



-- ============================================================
-- COMMISSION AGREEMENTS
-- ============================================================

MERGE INTO RAW.COMMISSION_AGREEMENTS T
USING RAW.STG_COMMISSION_AGREEMENTS S

ON T.AGREEMENT_ID = S.AGREEMENT_ID


WHEN MATCHED THEN UPDATE SET

T.ORGANIZER_ID = S.ORGANIZER_ID,
T.RESELLER_ID = S.RESELLER_ID,
T.COMMISSION_RATE = S.COMMISSION_RATE,
T.EFFECTIVE_FROM = S.EFFECTIVE_FROM,
T.EFFECTIVE_TO = S.EFFECTIVE_TO,
T.LOAD_TS = S.LOAD_TS,
T.SOURCE_SYSTEM = S.SOURCE_SYSTEM,
T.BATCH_ID = S.BATCH_ID,
T.UPDATED_AT = S.UPDATED_AT


WHEN NOT MATCHED THEN INSERT
(
AGREEMENT_ID,
ORGANIZER_ID,
RESELLER_ID,
COMMISSION_RATE,
EFFECTIVE_FROM,
EFFECTIVE_TO,
LOAD_TS,
SOURCE_SYSTEM,
BATCH_ID,
UPDATED_AT
)

VALUES
(
S.AGREEMENT_ID,
S.ORGANIZER_ID,
S.RESELLER_ID,
S.COMMISSION_RATE,
S.EFFECTIVE_FROM,
S.EFFECTIVE_TO,
S.LOAD_TS,
S.SOURCE_SYSTEM,
S.BATCH_ID,
S.UPDATED_AT
);



-- ============================================================
-- TICKET SALES
-- ============================================================

MERGE INTO RAW.TICKET_SALES T
USING RAW.STG_TICKET_SALES S

ON T.TICKET_ID = S.TICKET_ID


WHEN MATCHED THEN UPDATE SET

T.EVENT_ID = S.EVENT_ID,
T.CUSTOMER_ID = S.CUSTOMER_ID,
T.RESELLER_ID = S.RESELLER_ID,
T.SALES_CHANNEL = S.SALES_CHANNEL,
T.QUANTITY = S.QUANTITY,
T.UNIT_PRICE = S.UNIT_PRICE,
T.TOTAL_AMOUNT = S.TOTAL_AMOUNT,
T.PURCHASE_DATE = S.PURCHASE_DATE,
T.LOAD_TS = S.LOAD_TS,
T.SOURCE_SYSTEM = S.SOURCE_SYSTEM,
T.BATCH_ID = S.BATCH_ID,
T.UPDATED_AT = S.UPDATED_AT


WHEN NOT MATCHED THEN INSERT
(
TICKET_ID,
EVENT_ID,
CUSTOMER_ID,
RESELLER_ID,
SALES_CHANNEL,
QUANTITY,
UNIT_PRICE,
TOTAL_AMOUNT,
PURCHASE_DATE,
LOAD_TS,
SOURCE_SYSTEM,
BATCH_ID,
UPDATED_AT
)

VALUES
(
S.TICKET_ID,
S.EVENT_ID,
S.CUSTOMER_ID,
S.RESELLER_ID,
S.SALES_CHANNEL,
S.QUANTITY,
S.UNIT_PRICE,
S.TOTAL_AMOUNT,
S.PURCHASE_DATE,
S.LOAD_TS,
S.SOURCE_SYSTEM,
S.BATCH_ID,
S.UPDATED_AT
);