UPDATE CONTROL.LOAD_WATERMARK
SET LAST_TS = (
    SELECT MAX(UPDATED_AT)
    FROM RAW.STG_COMMISSION_AGREEMENTS
),
UPDATED_AT = CURRENT_TIMESTAMP()
WHERE TABLE_NAME = 'COMMISSION_AGREEMENTS';

UPDATE CONTROL.LOAD_WATERMARK
SET LAST_TS = (
    SELECT MAX(UPDATED_AT)
    FROM RAW.STG_CUSTOMERS
),
UPDATED_AT = CURRENT_TIMESTAMP()
WHERE TABLE_NAME = 'CUSTOMERS';

UPDATE CONTROL.LOAD_WATERMARK
SET LAST_TS = (
    SELECT MAX(UPDATED_AT)
    FROM RAW.STG_EVENTS
),
UPDATED_AT = CURRENT_TIMESTAMP()
WHERE TABLE_NAME = 'EVENTS';

UPDATE CONTROL.LOAD_WATERMARK
SET LAST_TS = (
    SELECT MAX(UPDATED_AT)
    FROM RAW.STG_ORGANIZERS
),
UPDATED_AT = CURRENT_TIMESTAMP()
WHERE TABLE_NAME = 'ORGANIZERS';

UPDATE CONTROL.LOAD_WATERMARK
SET LAST_TS = (
    SELECT MAX(UPDATED_AT)
    FROM RAW.STG_RESELLERS
),
UPDATED_AT = CURRENT_TIMESTAMP()
WHERE TABLE_NAME = 'RESELLERS';

UPDATE CONTROL.LOAD_WATERMARK
SET LAST_TS = (
    SELECT MAX(UPDATED_AT)
    FROM RAW.STG_RESELLER_DAILY_SALES
),
UPDATED_AT = CURRENT_TIMESTAMP()
WHERE TABLE_NAME = 'RESELLER_DAILY_SALES';

UPDATE CONTROL.LOAD_WATERMARK
SET LAST_TS = (
    SELECT MAX(UPDATED_AT)
    FROM RAW.STG_TICKET_SALES
),
UPDATED_AT = CURRENT_TIMESTAMP()
WHERE TABLE_NAME = 'TICKET_SALES';