name: b2b_event_ticketing

version: "1.0"

config-version: 2


profile: b2b_event_ticketing


model-paths:
  - models


analysis-paths:
  - analyses


test-paths:
  - tests


macro-paths:
  - macros


target-path: target

clean-targets:
  - target
  - dbt_packages


models:
  b2b_event_ticketing:

    staging:
      +materialized: view

    intermediate:
      +materialized: view

    marts:
      dimensions:
        +materialized: view
        +schema: ANALYTICS

      facts:
        +materialized: table
        +schema: ANALYTICS

    audit:
      +materialized: table
      +schema: AUDIT
