select
  {{ generate_surrogate_key(['reseller_id','event_id','ticket_type_id','sale_date','customer_email']) }} as reseller_sale_key,
  sale_date,
  reseller_id,
  reseller_name,
  reseller_region,
  event_id,
  event_name,
  event_type,
  ticket_type_id,
  ticket_name,
  upper(sales_channel) as sales_channel,
  quantity,
  unit_price,
  gross_amount,
  commission_rate,
  round(gross_amount * commission_rate / 100, 2) as commission_amount,
  round(gross_amount - (gross_amount * commission_rate / 100), 2) as net_amount,
  customer_email,
  currency,
  source_file,
  loaded_at
from {{ source('raw','RAW_RESELLER_SALES') }}
